// Package agentcontext decides what survives when a thread's history is replaced by
// a summary.
//
// The engine owns when to compact and where to cut; this package owns what a
// compaction keeps and how it reads. The split matters because the two answers
// change for different reasons: the cut is about byte budgets and provider
// limits, while the content is about what a model needs in order to carry on.
//
// Everything here is derived from what the runtime observed — the plan the model
// declared, the paths the tools wrote, the lookups that succeeded, the calls that
// failed. Nothing is generated by asking a model to summarize itself: a thread
// that can write its own summary can write "I verified this", which is the one
// claim a summary must never invent.
//
// Sections are rendered most-valuable-first because a byte budget cuts the tail.
// The order is not the order the roadmap lists them in; it is the order of what
// costs most to lose. Facts sit near the end because a lookup can be run again,
// while the goal cannot be recovered by any tool call.
package agentcontext

import (
	"fmt"
	"sort"
	"strings"
)

// Section names, in render order. They double as the identifiers reported in the
// compaction event, so a host can tell a summary that carried the goal from one
// that only had room for a transcript.
const (
	SectionTruth     = "truth_capsule"
	SectionGoals     = "goals"
	SectionTodos     = "todos"
	SectionFailures  = "failures"
	SectionChanges   = "changes"
	SectionCritical  = "critical_paths"
	SectionFacts     = "facts"
	SectionDigest    = "digest"
	SectionNarrative = "narrative"
)

// MarkerStart and MarkerEnd wrap a rendered summary inside the message that
// carries it.
//
// The markers are what makes a second compaction possible. Without them the
// previous summary is just another system message, and flattening it the way an
// ordinary message is flattened destroys in one line what the last compaction
// spent its whole budget preserving.
const (
	MarkerStart = "<qcode_summary>"
	MarkerEnd   = "</qcode_summary>"
)

// truncationNotice closes a summary a budget cut short. It mirrors the volatile
// context sections: a reader who cannot tell a cut from an absence will read the
// missing lines as an empty session.
const truncationNotice = "(this summary was cut to fit its budget; " +
	"earlier detail is gone, not undone)\n"

// CompactionChange is one path the thread wrote, and what has since been proved about it.
type CompactionChange struct {
	Path string
	Turn uint64
	// Read is whether the write rested on a read of the same path.
	Read bool
	// Verified is whether a passing verification has covered the path since.
	Verified bool
	// Diagnostics is whether a post-edit check still reports problems.
	Diagnostics bool
	// Stale means a restored workspace binding no longer supports the claim.
	Stale bool
}

// CompactionFact is one thing a lookup established, already rendered by its owner. The
// summary does not re-derive the wording: the evidence ledger already decided
// how a fact reads, and two spellings of the same fact would be worse than one.
type CompactionFact struct {
	Line string
}

// Todo is one step of the declared plan that is not finished.
type Todo struct {
	Title string
	// Status is the plan's own word for the step, as the model reported it.
	Status string
}

// Summary is what one compaction preserves.
//
// A zero Summary renders to nothing, which is the honest result for a thread
// that has done nothing worth remembering.
type Summary struct {
	// Window is how many messages this summary replaces. It is reported so a
	// reader can tell a summary of two messages from one of two hundred.
	Window int
	// Goal is what the thread is trying to do, in one line.
	Goal string
	// Todos are the plan steps still outstanding.
	Todos []Todo
	// DoneTodos counts the finished steps, so a shrinking list does not read as
	// a shrinking task.
	DoneTodos int
	// Failures are the attempts that did not work, so they are not repeated.
	Failures []Failure
	// Changes are the paths the thread wrote.
	Changes []CompactionChange
	// CriticalPaths are the paths the user or the plan pinned.
	CriticalPaths []string
	// Facts are what lookups established.
	Facts []CompactionFact
	// OmittedFacts is how many facts the entry limit left out.
	OmittedFacts int
	// Digest is the per-message running record of what was removed, newest first.
	Digest []string
	// OmittedDigest is how many digest lines the entry limit left out.
	OmittedDigest int
}

// Empty reports whether the summary has nothing to say.
func (s Summary) Empty() bool {
	return strings.TrimSpace(s.Goal) == "" && len(s.Todos) == 0 && len(s.Failures) == 0 &&
		len(s.Changes) == 0 && len(s.CriticalPaths) == 0 && len(s.Facts) == 0 &&
		len(s.Digest) == 0 && s.OmittedDigest == 0
}

// Render writes the summary, dropping whole sections from the end until it fits
// budget bytes. It reports the text, whether anything was dropped, and which
// sections made it in.
//
// Sections are dropped whole rather than cut mid-way: half a change list reads
// like a complete one, and a model that believes it has the full list of
// unverified paths will stop looking for the rest. The transcript is the one
// exception — it is a flat list of independent lines, so dropping its oldest
// entries loses nothing a reader would misread.
//
// A budget of zero or less means unbounded. A budget too small for even the
// wrapper is not honoured: the markers, the header and the notice are always
// written, because a compaction that silently produced nothing would leave the
// thread with no trace that history was dropped at all.
func (s Summary) Render(budget int) (string, bool, []string) {
	if s.Empty() {
		return "", false, nil
	}
	blocks := s.blocks()
	header := s.header()
	// The notice and the header are charged up front so a summary that runs out of
	// room can still say what it is and admit what it lost.
	room := unbounded
	if budget > 0 {
		room = max(0, budget-len(MarkerStart)-len(MarkerEnd)-2-len(truncationNotice)-len(header))
	}
	var body strings.Builder
	var kept []string
	truncated := false
	for _, block := range blocks {
		text := block.render(remaining(room, body.Len()))
		if text == "" {
			truncated = true
			continue
		}
		body.WriteString(text)
		kept = append(kept, block.name)
		if block.partial {
			truncated = true
		}
	}
	if body.Len() == 0 {
		truncated = true
	}
	var out strings.Builder
	out.WriteString(MarkerStart)
	out.WriteByte('\n')
	out.WriteString(header)
	out.WriteString(body.String())
	if truncated {
		out.WriteString(truncationNotice)
	}
	out.WriteString(MarkerEnd)
	return out.String(), truncated, kept
}

// header states what the summary stands in for. Without it the model reads a
// wall of structure with no clue that a conversation used to be there.
func (s Summary) header() string {
	if s.Window <= 0 {
		return "Summary of earlier work in this thread.\n"
	}
	return fmt.Sprintf(
		"Summary of earlier work in this thread; it replaces %d message(s).\n", s.Window,
	)
}

// unbounded is the room a renderer is given when there is no budget. It is a
// distinct value rather than zero because zero room is a real state — a budget
// entirely spent on the wrapper — and reading it as "no limit" is how a small
// budget ends up rendering everything.
const unbounded = -1

func remaining(room, used int) int {
	if room == unbounded {
		return unbounded
	}
	return max(0, room-used)
}

// block is one candidate section: its name, and a renderer that either fits in
// the room it is given or declines entirely.
type block struct {
	name string
	// partial is set by the renderer when it kept only part of its content.
	partial bool
	body    func(room int) (string, bool)
}

func (b *block) render(room int) string {
	text, partial := b.body(room)
	b.partial = partial
	return text
}

// blocks lists the sections that have something to say, in render order. A
// section with no content is left out rather than rendered empty, so a summary
// is never reported as truncated merely because the thread has no failures.
func (s Summary) blocks() []*block {
	candidates := []*block{
		fixed(SectionGoals, s.renderGoal()),
		fixed(SectionTodos, s.renderTodos()),
		fixed(SectionFailures, s.renderFailures()),
		fixed(SectionChanges, s.renderChanges()),
		fixed(SectionCritical, s.renderCritical()),
		fixed(SectionFacts, s.renderFacts()),
	}
	blocks := make([]*block, 0, len(candidates)+1)
	for _, candidate := range candidates {
		if candidate != nil {
			blocks = append(blocks, candidate)
		}
	}
	if len(s.Digest) > 0 || s.OmittedDigest > 0 {
		blocks = append(blocks, &block{name: SectionDigest, body: s.renderDigest})
	}
	return blocks
}

// fixed makes a section all-or-nothing: it renders only if it fits whole.
func fixed(name, text string) *block {
	if text == "" {
		return nil
	}
	return &block{name: name, body: func(room int) (string, bool) {
		if room != unbounded && len(text) > room {
			return "", false
		}
		return text, false
	}}
}

func (s Summary) renderGoal() string {
	goal := strings.TrimSpace(s.Goal)
	if goal == "" {
		return ""
	}
	return "Goal: " + collapse(goal) + "\n"
}

func (s Summary) renderTodos() string {
	if len(s.Todos) == 0 && s.DoneTodos == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("Still to do")
	if s.DoneTodos > 0 {
		fmt.Fprintf(&b, " (%d step(s) already done)", s.DoneTodos)
	}
	b.WriteString(":\n")
	for _, todo := range s.Todos {
		fmt.Fprintf(&b, "  %s", collapse(todo.Title))
		if todo.Status != "" {
			fmt.Fprintf(&b, " [%s]", todo.Status)
		}
		b.WriteByte('\n')
	}
	return b.String()
}

func (s Summary) renderFailures() string {
	if len(s.Failures) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("Already tried and failed, do not repeat blindly:\n")
	for _, failure := range s.Failures {
		fmt.Fprintf(&b, "  %s\n", failure.line())
	}
	return b.String()
}

func (s Summary) renderChanges() string {
	if len(s.Changes) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("Changed so far:\n")
	for _, change := range s.Changes {
		fmt.Fprintf(&b, "  %s (turn %d) — %s\n", change.Path, change.Turn, change.state())
	}
	return b.String()
}

// state says what is known about a change in words rather than flags, for the
// same reason the evidence section does: a model asked to close a gap should not
// have to decode a struct.
func (c CompactionChange) state() string {
	var notes []string
	switch {
	case c.Verified:
		notes = append(notes, "verified")
	default:
		notes = append(notes, "nothing verified it")
	}
	if !c.Read {
		notes = append(notes, "written without being read first")
	}
	if c.Diagnostics {
		notes = append(notes, "diagnostics still failing")
	}
	return strings.Join(notes, ", ")
}

func (s Summary) renderCritical() string {
	if len(s.CriticalPaths) == 0 {
		return ""
	}
	return "Critical paths: " + strings.Join(s.CriticalPaths, ", ") + "\n"
}

func (s Summary) renderFacts() string {
	if len(s.Facts) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("What lookups established:\n")
	for _, fact := range s.Facts {
		fmt.Fprintf(&b, "  %s\n", fact.Line)
	}
	if s.OmittedFacts > 0 {
		fmt.Fprintf(&b, "  (%d more not listed)\n", s.OmittedFacts)
	}
	return b.String()
}

const digestSectionHeader = "Removed history, newest first:"

// renderDigest writes removed ordinary messages newest first.
//
// Newest first is the whole point: the turns nearest the cut are the ones the
// next sample continues from, so when the budget runs out it is the distant past
// that goes. Writing them oldest-first would keep the beginning of a long
// session and drop the part that just happened.
func (s Summary) renderDigest(room int) (string, bool) {
	omitted := listedOmission(s.OmittedDigest)
	if len(s.Digest) == 0 && omitted == "" {
		return "", false
	}
	header := digestSectionHeader + "\n"
	if room != unbounded && len(header)+len(omitted) > room {
		return "", true
	}
	var b strings.Builder
	b.WriteString(header)
	partial := false
	for _, line := range s.Digest {
		entry := "  " + collapse(line) + "\n"
		if room != unbounded && b.Len()+len(entry)+len(omitted) > room {
			partial = true
			break
		}
		b.WriteString(entry)
	}
	b.WriteString(omitted)
	return b.String(), partial
}

func listedOmission(count int) string {
	if count <= 0 {
		return ""
	}
	return fmt.Sprintf("  (%d more not listed)\n", count)
}

// Carry extracts the summary body from a message that holds one, so the next
// compaction can pass it through instead of flattening it. It reports false for
// text that is not a summary.
func Carry(text string) (string, bool) {
	start := strings.Index(text, MarkerStart)
	if start < 0 {
		return "", false
	}
	rest := text[start+len(MarkerStart):]
	end := strings.LastIndex(rest, MarkerEnd)
	if end < 0 {
		return "", false
	}
	body := strings.TrimSpace(rest[:end])
	if body == "" {
		return "", false
	}
	return body, true
}

// CarriedDigest extracts the structured digest from a compacted summary so the
// next compaction can merge it. Carry() only means the message is a summary
// and must not be flattened as one ordinary line. A summary with no digest
// section still reports ok with an empty list.
func CarriedDigest(text string) (lines []string, omitted int, ok bool) {
	body, ok := Carry(text)
	if !ok {
		return nil, 0, false
	}
	start := strings.Index(body, digestSectionHeader)
	if start < 0 {
		return nil, 0, true
	}
	rest := body[start+len(digestSectionHeader):]
	for _, line := range strings.Split(rest, "\n") {
		line = strings.TrimRight(line, "\r")
		if strings.TrimSpace(line) == "" {
			continue
		}
		if count, parsed := parseListedOmission(line); parsed {
			return lines, count, true
		}
		if !strings.HasPrefix(line, "  ") {
			break
		}
		lines = append(lines, strings.TrimSpace(line))
	}
	return lines, 0, true
}

func parseListedOmission(line string) (int, bool) {
	var count int
	if _, err := fmt.Sscanf(strings.TrimSpace(line), "(%d more not listed)", &count); err != nil {
		return 0, false
	}
	return count, true
}

// collapse folds whitespace so one wrapped message cannot occupy ten lines of a
// summary that is meant to be scannable.
func collapse(text string) string {
	return strings.Join(strings.Fields(text), " ")
}

// SortChanges orders changes so the ones still owing proof come first, then
// oldest, then by path. A path changed four turns ago and still unverified is
// more pressing than one changed and verified a moment ago.
func SortChanges(changes []CompactionChange) {
	sort.Slice(changes, func(i, j int) bool {
		left, right := changes[i], changes[j]
		if left.Verified != right.Verified {
			return !left.Verified
		}
		if left.Turn != right.Turn {
			return left.Turn < right.Turn
		}
		return left.Path < right.Path
	})
}
