// Command webprotocolgen generates the published Web Host transport contract.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"

	webhost "github.com/fwtllh-png/QCode/internal/host"
	"github.com/fwtllh-png/QCode/internal/runtime/protocol"
)

type generated struct {
	contract   []byte
	goSource   []byte
	typeScript []byte
}

func main() {
	output := flag.String(
		"output",
		"docs/protocol/web-host.contract.json",
		"generated Web Host contract manifest",
	)
	typeScript := flag.String(
		"typescript",
		"web/src/protocol/web-host.generated.ts",
		"generated TypeScript route contract",
	)
	goOutput := flag.String(
		"go-output",
		"internal/host/unary_routes.generated.go",
		"generated Go unary route bindings",
	)
	check := flag.Bool("check", false, "fail if the committed output is stale")
	flag.Parse()

	content, err := generate()
	if err == nil {
		outputs := []struct {
			path    string
			content []byte
		}{
			{*output, content.contract},
			{*typeScript, content.typeScript},
			{*goOutput, content.goSource},
		}
		for _, generated := range outputs {
			if *check {
				err = checkFile(generated.path, generated.content)
			} else {
				err = writeFile(generated.path, generated.content)
			}
			if err != nil {
				break
			}
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "generate Web Host contract:", err)
		os.Exit(1)
	}
}

func generate() (generated, error) {
	contract := webhost.Contract()
	manifest, err := json.MarshalIndent(contract, "", "  ")
	if err != nil {
		return generated{}, err
	}
	var routes []string
	for _, route := range contract.Routes {
		if route.Method == "POST" && strings.HasPrefix(route.Path, "/api/v1/") {
			path := strings.TrimPrefix(route.Path, "/api/v1/")
			routes = append(routes, path)
		}
	}
	sort.Strings(routes)
	goSource, err := generateGoRoutes(routes)
	if err != nil {
		return generated{}, err
	}
	var typeScript strings.Builder
	typeScript.WriteString("// Code generated by webprotocolgen. DO NOT EDIT.\n\n")
	fmt.Fprintf(
		&typeScript,
		"export const webProtocolVersion = %d as const;\n\n",
		contract.ProtocolVersion,
	)
	typeScript.WriteString("export const webRPCRoutes = [\n")
	for _, route := range routes {
		fmt.Fprintf(&typeScript, "  %q,\n", route)
	}
	typeScript.WriteString("] as const;\n\n")
	typeScript.WriteString(
		"export type WebRPCRoute = (typeof webRPCRoutes)[number];\n",
	)
	typeScript.WriteString("\nexport const webEventKinds = [\n")
	for _, kind := range protocol.EventKinds() {
		fmt.Fprintf(&typeScript, "  %q,\n", kind)
	}
	typeScript.WriteString("] as const;\n\n")
	typeScript.WriteString(
		"export type WebEventKind = (typeof webEventKinds)[number];\n",
	)
	return generated{
		contract:   append(manifest, '\n'),
		goSource:   goSource,
		typeScript: []byte(typeScript.String()),
	}, nil
}

func generateGoRoutes(routes []string) ([]byte, error) {
	var source strings.Builder
	source.WriteString("// Code generated by webprotocolgen. DO NOT EDIT.\n\n")
	source.WriteString("package host\n\n")
	source.WriteString("func unaryRouteHandler(path string) (unaryHandler, bool) {\n")
	source.WriteString("\tswitch path {\n")
	handlers := make(map[string]string, len(routes))
	for _, route := range routes {
		handler, err := handlerName(route)
		if err != nil {
			return nil, err
		}
		if previous := handlers[handler]; previous != "" {
			return nil, fmt.Errorf(
				"routes %q and %q produce the same handler %q",
				previous,
				route,
				handler,
			)
		}
		handlers[handler] = route
		fmt.Fprintf(
			&source,
			"\tcase %q:\n\t\treturn (*Server).%s, true\n",
			route,
			handler,
		)
	}
	source.WriteString("\tdefault:\n\t\treturn nil, false\n\t}\n")
	source.WriteString("}\n")
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated Go routes: %w", err)
	}
	return formatted, nil
}

func handlerName(route string) (string, error) {
	if strings.Trim(route, "/-") != route ||
		strings.Contains(route, "//") ||
		strings.Contains(route, "--") {
		return "", fmt.Errorf("route %q has invalid handler segments", route)
	}
	parts := strings.FieldsFunc(route, func(value rune) bool {
		return value == '/' || value == '-'
	})
	if len(parts) == 0 || parts[0] == "" {
		return "", fmt.Errorf("route %q has no handler name", route)
	}
	var name strings.Builder
	name.WriteString(parts[0])
	for _, part := range parts[1:] {
		if part == "" {
			return "", fmt.Errorf("route %q has an empty handler segment", route)
		}
		name.WriteString(strings.ToUpper(part[:1]))
		name.WriteString(part[1:])
	}
	if !token.IsIdentifier(name.String()) {
		return "", fmt.Errorf("route %q produces invalid handler %q", route, name.String())
	}
	return name.String(), nil
}

func checkFile(path string, expected []byte) error {
	current, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if !bytes.Equal(current, expected) {
		return errors.New(path + " is stale; run make web-protocol")
	}
	return nil
}

func writeFile(path string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".web-host-schema-*")
	if err != nil {
		return err
	}
	name := temporary.Name()
	defer os.Remove(name)
	if err := temporary.Chmod(0o644); err != nil {
		_ = temporary.Close()
		return err
	}
	if _, err := temporary.Write(content); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(name, path)
}
